### ISSUE TITLE
Help with using you MDPSolver

### ISSUE THREAD

**Issue by BrunoJeric** [areenberg/MDPSolver#2]
Hello,
Quick question about you repo, are you still developing this solver or it is staled. Actually I am more interested in CBMmodel  and am wondering have you been around to support it in to solve since modifiedPolicyIteration function only works with TBMmodel.

**Comment by areenberg** [comment]
Hi,
Thank you for your question - of course we can help you to get our solver up and running. The CBMmodel should be working “out of the box”. Can you give us some more information about the issue? If you send us your parameters, we will try to replicate the problem.
Best regards, Anders

**Comment by areenberg** [comment]
Hi Bruno,
No problem :-)
I will contact you from my DTU work mail.

Best regards,
Anders

**Comment by BrunoJeric** [comment]
fixed
