### ISSUE TITLE
MacOS/Linux compatibility

### ISSUE THREAD

**Issue by mazqtpopx** [areenberg/MDPSolver#3]
Hi,

Thanks for the package - just what I was looking for! Unfortunately I couldn't manage to get it to work :( 

I tried running on macOS an get:
```import mdpsolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mariusz/.pyenv/versions/3.10.15/lib/python3.10/site-packages/mdpsolver/__init__.py", line 1, in <module>
    from mdpsolver.model import model
  File "/Users/mariusz/.pyenv/versions/3.10.15/lib/python3.10/site-packages/mdpsolver/model.py", line 1, in <module>
    from mdpsolver import solvermodule
ImportError: cannot import name 'solvermodule' from partially initialized module 'mdpsolver' (most likely due to a circular import) (/Users/mariusz/.pyenv/versions/3.10.15/lib/python3.10/site-packages/mdpsolver/__init__.py)
```
when I try to import it. (I know you, didn't specify macOS works)

I also tried on Ubuntu 20.04, python3.10 but get:
```ImportError: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found```
when importing the module
when I run ldd --version I get
```ldd (Ubuntu GLIBC2.31-0ubuntu9.16) 2.31``` 
hence there is a mismatch in glib - you built it with Ubuntu 21.10?
I will likely move on but maybe you can specify that Ubuntu 21.10 or greater is required? :)

**Comment by areenberg** [comment]
Hi @mazqtpopx,

Thank you for your interest in MDPSolver - I am sorry to hear that the package is not (currently) working on your machine(s). If you're up for it, you can try to compile and replace the SO-file for Python 3.10 within the package. Here are the steps:

1. Install pybind11: `pip install pybind11`.
2. Clone the repository and navigate to `CPP_Source_Code`.
3. Assuming you have g++ installed, compile the SO-file by running: 
```
g++ -O3 -fopenmp -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` *.cpp -o solvermodule`python3-config --extension-suffix`
```
4. You should now see an SO-file `solvermodule.cpython-310-x86_64-linux-gnu.so`. Use `pip show mdpsolver` to locate the package on your machine (e.g. `.local/lib/python3.10/site-packages/mdpsolver/`).
5. Navigate to the directory and replace the SO-file.
 
Let me know if this works.
You might be able to follow similar steps on macOS.

BR,
Anders

**Comment by mazqtpopx** [comment]
Thanks for the quick response @areenberg 

Yep that worked on Ubuntu 20.04. NB: needed to install python3.10-dev to have python3.10-config for the build. Will test on macOS later :)
